config/routes.rb
Rails.application.routes.draw do

  # resources :categories do
  #   resources :articles
  # end
  root to: 'welcome#index'

  get "/categories/:category_id/articles", to: "articles#index", as: "category_articles"
  post "/categories/:category_id/articles", to: "articles#create"
  get "/categories/:category_id/articles/new", to: "articles#new", as: "new_category_article"
  get "/categories/:category_id/articles/:id/edit", to: "articles#edit", as: "edit_category_article"
  get "/categories/:category_id/articles/:id", to: "articles#show", as: "category_article"
  patch "/categories/:category_id/articles/:id", to: "articles#update"
  put "/categories/:category_id/articles/:id", to: "articles#update"
  delete "/categories/:category_id/articles/:id", to: "articles#destroy"
  get "/categories", to: "categories#index", as:"categories"
  post "/categories", to: "categories#create"
  get "/categories/new", to: "categories#new", as: "new_category"
  get "/categories/:id/edit", to: "categories#edit", as: "edit_category"
  get "/categories/:id", to: "categories#show", as: 'category'



end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def edit
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @category
    else
      render "categories/index"
    end
  end

  def create
    @category = Category.find(params[:category_id])
    @article = @category.articles.create(article_params)
    if request.xhr?
      render @article, layout: false
    else
      redirect_to category_path(@category)
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to category_path(@category)
  end

  private
  def article_params
    params.require(:article).permit(:title, :email, :body, :cost_in_dollars)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
 end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    if @category = Category.find_or_create_by(category_params)
      redirect_to @category
    else
      render 'new'
    end
  end

  private
  def category_params
    params.require(:category).permit(:title)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<table>
  <tr>
  <th>Title</th>
    <td><%= article.title %></td>
    <td> <%= link_to "Edit", edit_category_article_path(@category, article) %> </td>
    <td> <%= link_to "Delete", category_article_path(@category, article),
        method: :delete,
        data: { confirm: "Are you sure?"} %> </td>
    </tr>
  </tr>
</table>
<p>
  <strong>Body:</strong>
  <%= article.body %>
</p>
<p>
  <strong>Cost in dollars:</strong>
  <%= article.cost_in_dollars %>
</p>
<p>
  <strong>Email:</strong>
  <%= article.email %>
</p>

app/views/articles/_form.html.erb
<%= form_for([@category, @article || @category.articles.new ], remote: true) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
    <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
    <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
    <p>
    <%= f.label :cost_in_dollars %><br>
    <%= f.text_field :cost_in_dollars %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render 'form' %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation" >
      <h2>
        <%= pluralize(@category.errors.count, "error") %>
        prohibited
        this category from being saved:
      </h2>
      <ul>
        <% @category.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>
<%= render 'form' %>
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories:</h1>

<table>
  <tr>
    <th>Title</th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td> <%= category.title %></td>
      <td> <%= link_to "Show", category_path(category) %> </td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1> catgories/new!  yayayasya </h1>

<%= render 'form' %>
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1>Categories:</h1>
  <p>
    <strong>Title:</strong>
    <%= @category.title %>
  </p>

  <h2>Articles:</h2>
  <div id="article_list">
  <%= render @category.articles %>
  </div>

  <h2>Add an article</h2>
  <%= render 'articles/form' %>

<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraigslistJr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1> welcome </h1>
<%= link_to 'Craigslist jr.', controller: 'categories' %>